%%  Sau MATLAB Colony Analyzer Toolkit
%
%%  LinearInNorm.m

%   Author: Saurin Parikh, February 2019
%   dr.saurin.parikh@gmail.com

%   Linear Interpolation to predict plate background using control colony
%   pixel counts.

%   IL = 1 : Interleave
%   IL = 0 : No Interleave

%%

    function data_fit = LinearInNorm(hours,n_plates,p2c_info,cont_name,...
        tablename_p2o,tablename_jpeg,IL)
    
        connectSQL;
        
        for ii = 1:length(hours)
            temp = [];
            for iii = 1:length(n_plates.x6144plate_1)

                pos.all = fetch(conn, sprintf(['select a.pos ',...
                    'from %s a ',...
                    'where %s = %d ',...
                    'order by %s, %s'],...
                    p2c_info(1,:),...
                    p2c_info(2,:),...
                    n_plates.x6144plate_1(iii),...
                    p2c_info(3,:),...
                    p2c_info(4,:)));

                pos.cont = fetch(conn, sprintf(['select a.pos ',...
                    'from %s a, %s b ',...
                    'where a.pos = b.pos and %s = %d and a.orf_name = ''%s'' ',...
                    'order by %s, %s'],...
                    tablename_p2o,...
                    p2c_info(1,:),...
                    p2c_info(2,:),...
                    n_plates.x6144plate_1(iii),...
                    cont_name,...
                    p2c_info(3,:),...
                    p2c_info(4,:)));

                avg_data = fetch(conn, sprintf(['select a.pos, a.hours, a.average ',...
                    'from %s a, %s b ',...
                    'where a.pos = b.pos and hours = %d and %s = %d ',...
                    'order by %s, %s'],...
                    tablename_jpeg,...
                    p2c_info(1,:),...
                    hours(ii),...
                    p2c_info(2,:),...
                    n_plates.x6144plate_1(iii),...
                    p2c_info(3,:),...
                    p2c_info(4,:)));

        %%  CALCULATE BACKGROUND

                cont_pos = col2grid(ismember(pos.all.pos, pos.cont.pos));
                cont_avg = col2grid(avg_data.average).*cont_pos;

                cont_avg(cont_avg == 0) = NaN;

                bg{iii} = LIHeart(cont_avg,cont_pos,IL);
%                 bg{iii} = LIHeart96(cont_avg,cont_pos,IL);
                bg{iii}(bg{iii} == 0) = NaN;
                temp = abs([temp; [pos.all.pos, ones(length(pos.all.pos),1)*hours(ii),...
                    bg{iii}, avg_data.average, avg_data.average./bg{iii}]]);
            end
            data_fit{ii} = temp;
        end
    end
    
%%  END    
    
